FROM node:lts-alpine

WORKDIR /frontend

COPY package.json /frontend/package.json
COPY package-lock.json /frontend/package-lock.json
RUN npm install
RUN npm install @vue/cli@latest -g

CMD ["npm", "run", "serve"]