version: '3.5'

services:

  db:
    container_name: mongo
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    #volumes:
    #  - './db:/data/db'

  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    restart: on-failure
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: default
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: password
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    ports:
      - 8443:8081
    depends_on:
      - db

  backend:
    container_name: flask
    build: ./backend
    restart: on-failure
    environment:
      - FLASK_SERVER_PORT=5000
    volumes:
      - ./backend:/backend
    depends_on:
      -  db

  
  frontend:
    container_name: "node"
    build: ./frontend
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/frontend
    ports:
      - "8001:8001"

  web:
    container_name: nginx
    image: nginx:latest
    restart: on-failure
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    environment: 
      - FLASK_SERVER_ADDR=backend:5000   
    volumes:
      - ./nginx/:/tmp/ 
    ports:
      - 880:80
      - 4443:443
    depends_on:
      - backend